apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer
  ports:
    - port: 14000
      targetPort: 14000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: producer
  labels:
    name: producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      # 此处需要
      #kubectl create secret docker-registry registry-pull-secret --namespace=default \
      #--docker-server=192.168.100.249 --docker-username=admin \
      #--docker-password=Harbor12345 --docker-email=xcp.email@gmail.com
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: producer
          image: 192.168.100.249/k8s/producer:latest
          env:
            - name: APP_NAME
              value: "eureka"
            - name: APP_OPTS
              value: "--registerWithEureka=true
                      --fetchRegistry=true
                      --eureka.instance.preferIpAddress=true
                      --eureka.client.serviceUrl.defaultZone=http://eureka-0.${APP_NAME}:7000/eureka/,http://eureka-1.${APP_NAME}:7000/eureka/,http://eureka-2.${APP_NAME}:7000/eureka/"
          ports:
            - containerPort: 14000