version: "3"
services:
  eureka-server:
    image: 192.168.1.100/k8s/eureka:latest
    ports:
      - "7000:7000"
    environment:
      - APP_OPTS=--eureka.instance.hostname=eureka-server --eureka.instance.preferIpAddress=true --eureka.client.serviceUrl.defaultZone=http://eureka-server:7000/eureka/
    networks:
      - cloud

  producer-server:
    image: 192.168.1.100/k8s/producer:latest
    ports:
      - "14000:14000"
    environment:
      - APP_OPTS=--registerWithEureka=true --fetchRegistry=true --eureka.instance.preferIpAddress=true --eureka.client.serviceUrl.defaultZone=http://eureka-server:7000/eureka/
    networks:
      - cloud
    depends_on:
      - eureka-server

  consumer-server:
    image: 192.168.1.100/k8s/consumer:latest
    ports:
      - "15000:15000"
    environment:
      - APP_OPTS=--registerWithEureka=true --fetchRegistry=true --eureka.instance.preferIpAddress=true --eureka.client.serviceUrl.defaultZone=http://eureka-server:7000/eureka/
    networks:
      - cloud
    depends_on:
      - eureka-server

networks:
  cloud:
    driver: bridge