apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - port: 15000
      targetPort: 15000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      # 此处需要
      #kubectl create secret docker-registry registry-pull-secret --namespace=default \
      #--docker-server=192.168.100.249 --docker-username=admin \
      #--docker-password=Harbor12345 --docker-email=xcp.email@gmail.com
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: producer
          image: 192.168.100.249/k8s/consumer:latest
          env:
            - name: APP_NAME
              value: "eureka"
            - name: APP_OPTS
              value: "--registerWithEureka=true
                      --fetchRegistry=true
                      --eureka.instance.preferIpAddress=true
                      --eureka.client.serviceUrl.defaultZone=http://eureka-0.${APP_NAME}:7000/eureka/,http://eureka-1.${APP_NAME}:7000/eureka/,http://eureka-2.${APP_NAME}:7000/eureka/"
          ports:
            - containerPort: 15000