spring:
  application:
    name: consumer
server:
  port: 15000
eureka:
  instance:
    #以IP注册进eureka,不以ID注册
    prefer-ip-address: true
  client:
    #注册到eureka为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 本地开发
      defaultZone: http://localhost:7000/eureka/
      # docker-compose
      #defaultZone: http://eureka-server:${server.port}/eureka/
      # k8s
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:7000/eureka/,http://eureka-1.eureka.default.svc.cluster.local:7000/eureka/,http://eureka-2.eureka.default.svc.cluster.local:7000/eureka/
