server:
  port: 7000

#spring:
#  application:
#    name: eureka

eureka:
  instance:
#    appname: ${spring.application.name}
    prefer-ip-address: false
  server:
    # eureka默认开启自我保护模式，导致已经不存在的实例还是会显示再eureka上，并继续提供服务。关闭方法如下
    enable-self-preservation: false
    #5秒清理一次，eureka会在一段时间内没有接收到心跳，就删除注册的实例
    eviction-interval-timer-in-ms: 5000
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

    # 是否从eureka上获取注册信息
    fetch-registry: false
    # 表示是否注册自身到eureka服务器
    register-with-eureka: false